package random

import "crypto/rand"

// Bytes is a function that returns a random generated byte slice with the given size.
func Bytes(size int) ([]byte, error) {
	// allocate memory
	salt := make([]byte, size)

	// generate random bytes
	_, err := rand.Read(salt)
	if err != nil {
		return nil, err
	}

	return salt, nil
}
